#!/bin/bash
source $(dirname "$0")/lib/init

# ------------------------------------------------------------------
# This script wraps docker-compose to provide environment based
# defaults and added functionality.
#
# Use it from the project root just like docker-composer
#
# example:
#
# scripts/dev up
# ------------------------------------------------------------------

COMMON="-f docker-compose.yml -f docker-compose.dev.yml"

docker-compose $COMMON "$@"
